### ISSUE TITLE
npm run init安装依赖到api2x的xss卡住然后报错

### ISSUE THREAD

**Issue by ithinco** [jianliaoim/talk-os#11]
`> ./init.sh

Install talk-api2x dependencies
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! cb() never called!`

Mac el captain
npm 3.7.3
node 5.9.0

log：
`npm http request GET https://registry.npmjs.org/xss

npm http 304 https://registry.npmjs.org/axon

npm http 304 https://registry.npmjs.org/apn

npm http 304 https://registry.npmjs.org/async

npm http 200 https://registry.npmjs.org/coffee-script

npm http 200 https://registry.npmjs.org/config

npm http 200 https://registry.npmjs.org/bluebird

npm http 304 https://registry.npmjs.org/charset

npm http 304 https://registry.npmjs.org/cookie-parser

npm http 304 https://registry.npmjs.org/err1st

npm http 304 https://registry.npmjs.org/connect-redis

npm http 304 https://registry.npmjs.org/cron

npm http 304 https://registry.npmjs.org/hat

npm http 304 https://registry.npmjs.org/hiredis

npm http 304 https://registry.npmjs.org/ejs

npm http 304 https://registry.npmjs.org/graceful-logger

npm http 200 https://registry.npmjs.org/body-parser

npm http 304 https://registry.npmjs.org/inflection

npm http 304 https://registry.npmjs.org/xss

npm http 304 https://registry.npmjs.org/talk-services

npm http 304 https://registry.npmjs.org/mongoosastic

npm http 304 https://registry.npmjs.org/i18n

npm http 304 https://registry.npmjs.org/he

npm http 304 https://registry.npmjs.org/jsonwebtoken

npm http 304 https://registry.npmjs.org/moment-timezone

npm http 304 https://registry.npmjs.org/express

npm http 304 https://registry.npmjs.org/uuid

npm http 304 https://registry.npmjs.org/request

npm http 304 https://registry.npmjs.org/marked

npm http 304 https://registry.npmjs.org/htmlparser2

npm http 304 https://registry.npmjs.org/jschardet

npm http 304 https://registry.npmjs.org/pinyin

npm http 304 https://registry.npmjs.org/juice

npm http 304 https://registry.npmjs.org/redis

npm http 304 https://registry.npmjs.org/serve-favicon

npm http 304 https://registry.npmjs.org/shortid

npm http 304 https://registry.npmjs.org/require-dir

npm http 304 https://registry.npmjs.org/morgan

npm http 304 https://registry.npmjs.org/lodash

npm http 304 https://registry.npmjs.org/talk-lexer

npm http 304 https://registry.npmjs.org/sundae

npm http 304 https://registry.npmjs.org/mongoose

npm http 304 https://registry.npmjs.org/mailgun-js

npm http 304 https://registry.npmjs.org/validator

npm http 304 https://registry.npmjs.org/limbo

npm http 200 https://registry.npmjs.org/iconv-lite

npm http 304 https://registry.npmjs.org/node-push

npm http 200 https://registry.npmjs.org/moment

npm http 200 https://registry.npmjs.org/jade

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

npm http 304 https://registry.npmjs.org/multer

npm http 304 https://registry.npmjs.org/json-mask

npm ERR! cb() never called!

npm info lifecycle talk-os@1.0.0~postinit: talk-os@1.0.0

npm info ok `

**Comment by sailxjx** [comment]
用 node 4.x 和 npm 2.x 试试吧

**Comment by ithinco** [comment]
@sailxjx 

`npm ERR! Darwin 15.4.0

npm ERR! argv "/Users/guance/.nvm/versions/node/v4.4.2/bin/node" 

"/Users/guance/.nvm/versions/node/v4.4.2/bin/npm" "start"

npm ERR! node v4.4.2

npm ERR! npm  v2.15.0

npm ERR! code ELIFECYCLE

npm ERR! talk-os@1.0.0 start: `coffee app.coffee`

npm ERR! Exit status 1

npm ERR! 
npm ERR! Failed at the talk-os@1.0.0 start script 'coffee app.coffee'.

npm ERR! This is most likely a problem with the talk-os package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     coffee app.coffee

npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs talk-os

npm ERR! Or if that isn't available, you can get their info via:

npm ERR! 

npm ERR!     npm owner ls talk-os

npm ERR! There is likely additional logging output above.`

**Comment by sailxjx** [comment]
哦，你需要预先安装 `npm i -g coffeescript`，并且确保 `coffee` 命令存在你的环境变量中

安装之后输入 `coffee` 试一下会不会报错吧，如果不会，项目应该就可以正常跑了

**Comment by ithinco** [comment]
@sailxjx 事先安装过`npm i -g coffeescript`，`coffee`也不报错，但是npm start还是报上面的错误。

**Comment by ithinco** [comment]
搞定了 `npm install --save coffee-script`

**Comment by sailxjx** [comment]
@ithinco 确实是启动的时候 config 模块依赖 coffee-script，感谢反馈

https://github.com/jianliaoim/talk-os/commit/09026ef3e9f5c0c87fac1a1d1a982ec6ee933525 这个 commit 已经修复了这个问题
