### ISSUE TITLE
How to enable the live reload function?

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#16]
我看到talk-os里分别有talk-web和talk-account里的package.json配置了watch脚本，但是当启动工程后，我分别在上面两个工程下用npm run watch去开启webpack的热替换功能，但其实没有任何作用，这个非常影响开发效率，希望能够给予解答。

**Comment by ShadowZheng** [comment]
@Boshen 看了下你改了talk-web和talk-account中package.json增加了watch任务，但是我启动后，改懂talk-account里的coffee或者css文件，并没有hot module replace的效果，没有实际解决问题啊。烦请查看一下。

**Comment by Boshen** [comment]
我想起来了。。 我们的代码实际上是没有hmr的， 你仔细看的话会发现我们没有用任何hmr的loader, 我们也没有用redux。

**Comment by ShadowZheng** [comment]
```coffeescript
gulp.task 'webpack-dev', (cb) ->
  webpackDev = require './client/packing/webpack-dev'
  webpackServer =
    publicPath: '/'
    hot: true
    stats:
      colors: true
  info =
    __dirname: __dirname
    env: config.env

  compiler = webpack (webpackDev info)
  server = new WebpackDevServer compiler, webpackServer

  server.listen config.webpackDevPort, '0.0.0.0', (err) ->
    if err?
      throw new gutil.PluginError("webpack-dev-server", err)
    gutil.log "[webpack-dev-server] is starting..."
    cb()
```
那你们开发模式不可能改一次代码就重新build一次，然后再重启服务器把？这个是我截图你们关于webpackserver的配置，你们应该是配置好的，还请帮忙看一下，万分感谢～

**Comment by Boshen** [comment]
这个项目的配置是最后部署服务器的配置， 要改成本地开发配置的话你得自己改api路径， 还需要配置nginx。

**Comment by ShadowZheng** [comment]
@Boshen OMG~, 期待你们能出个文档，这样开发人员知道怎么去做。
