### ISSUE TITLE
有没有IOS的SDK，能开源出来吗？

### ISSUE THREAD

**Issue by m430** [jianliaoim/talk-os#17]
RT，看了简聊的代码，后台通讯的服务都写了，但想做个IOS版本，但是没有SDK，请问能不能开源SDK或者客户端代码也可以啊

@Boshen @jiyinyiyong

**Comment by jiyinyiyong** [comment]
@sailxjx

**Comment by sailxjx** [comment]
@ShadowZheng 感谢关注，我们下周会讨论一下简聊客户端开源的方案。
@shirejiang @conan007ai @zhangxiaolian1991

**Comment by ShadowZheng** [comment]
@sailxjx 谢谢你的回复，希望你们能越做越好，把简聊打造成一个中国最牛的IM平台。

**Comment by deweydu** [comment]
期待开源iOS版本

**Comment by wlanjie** [comment]
@deweydu 不要着急,应该是最近这两个星期会开源出来的

**Comment by deweydu** [comment]
太好了，密切关注。
