### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#22]
本地搭建的jianliao，注册的用户，无法上传文件，我发现上传服务会发送到striker.teambition.com，报401的错，我想应该是本地注册的用户无法授权到上传服务网站，这个能解决吗？还是说上传服务要替换成我们自己的？

@sailxjx @Boshen

**Comment by sailxjx** [comment]
#23

**Comment by feit** [comment]
这个striker使用的开源存储服务吗？
