### ISSUE TITLE
小艾无法自动回复

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#23]
@sailxjx 

看到你之前的issue说开源进程中移除了文件上传和小艾自动回复这部分，这个不能开源吗？
如果不能开源，能否说下你们talk.ai的实现方式？有没有开源产品可以替代这部分功能呢？

希望能得到回复，感谢～

**Comment by sailxjx** [comment]
小艾自动回复用的是[图灵机器人](http://www.tuling123.com/)（他们也不给我广告费），是收费服务，如果确实需要的话可以自行接入，在[这里](https://github.com/jianliaoim/talk-os/blob/master/talk-api2x/server/observers/message.coffee#L341)将新消息转发给[talkai](https://github.com/jianliaoim/talk-services/blob/master/src/services/talkai.coffee)就行。
文件上传因为是用的 Teambition 的服务，需要签名，而且也会产生一定的存储费用，所以就不方便放到开源的代码中来了。如果需要文件上传，修改一下前端上传的代码，发送到自己的服务器吧

**Comment by ShadowZheng** [comment]
感谢您的回复，我知道该怎么做了 ：）
