### ISSUE TITLE
怎么开启邀请发送邮件的功能？

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#25]
RT. 现在邀请成员，没有发送邮件。

@sailxjx

**Comment by sailxjx** [comment]
邀请邮件现在是关闭的，你可以删掉这一行 https://github.com/jianliaoim/talk-os/blob/master/talk-api2x/server/mailers/base.coffee#L41 来开启，下面的代码改成将请求发送到你自己的邮件服务商

**Comment by ShadowZheng** [comment]
@sailxjx 请问你们用的是什么邮件服务商？

**Comment by sailxjx** [comment]
mailgun

**Comment by ShadowZheng** [comment]
在base.coffee中有这段代码：
```javascript

mailguy = require('axon').socket('push')
mailguy.connect(config.mailguy)
```

config.mailguy 里面都配置了什么参数啊？

@sailxjx

**Comment by sailxjx** [comment]
mailguy 是我们自己开发的邮件服务进程，你不要用这个。将 _send 方法中的 email 对象发送到你自己的服务，然后转发到你想要的邮件服务里去。

**Comment by ShadowZheng** [comment]
按照mailgun集成即可。
