### ISSUE TITLE
简聊开发中怎么调试？

### ISSUE THREAD

**Issue by ShadowZheng** [jianliaoim/talk-os#26]
简聊代码我看了也不少了，现在没有HMR功能，很影响开发效率，这个就不说了，有时间我自己解决吧，但是有时候改bug调试起来很痛苦，还是基本用console的方式调试，请问你们有更好的方式吗？

我指的是server端哦。

@sailxjx  请指教，谢谢啦~  : )

**Comment by sailxjx** [comment]
server 端一般就用 console 来调试，你可以用 node-dev 来辅助自动重启。

如果你能折腾，可以去试试 node-inspector，不过我觉得太麻烦，不如 console 省事

**Comment by ShadowZheng** [comment]
好吧，谢谢哈，这个问题可以关闭了
