### ISSUE TITLE
./notification Module 找不到

### ISSUE THREAD

**Issue by motcwang** [jianliaoim/talk-os#30]
如题，日志如下：

```
main.a83421cf.js:1457 Uncaught Error: Cannot find module "./notification"
webpackMissingModule @ main.a83421cf.js:1457
(anonymous function) @ main.a83421cf.js:1457
__webpack_require__ @ vendor.88a6ec1f.js:51
(anonymous function) @ main.a83421cf.js:34
__webpack_require__ @ vendor.88a6ec1f.js:51
webpackJsonpCallback @ vendor.88a6ec1f.js:22
(anonymous function) @ main.a83421cf.js:1
```

**Comment by icezohu** [comment]
今天搭环境遇到同样的问题，请问有解决办法了没有？感谢！

**Comment by Boshen** [comment]
看不出具体的问题在哪里。。 :crying_cat_face:

**Comment by icezohu** [comment]
发现两个bug：
![image](https://cloud.githubusercontent.com/assets/3282625/20389450/993eae94-ad04-11e6-8a64-8f0490450298.png)
/talk-os/talk-web/client/updater/notification.coffee
line: 149
or 和 = 中间不能有空格，gulp过不去有提示。
![image](https://cloud.githubusercontent.com/assets/3282625/20389496/d8052fea-ad04-11e6-8dd5-fd41df5c3d6d.png)
/talk-os/talk-web/client/util/analytics.coffee
line: 1
不知是不是cookie_js版本改了，直接require到的对象不能直接用，需要引用下一级的cookie对象才行。

**Comment by sailxjx** [comment]
@Boshen 业界良心

**Comment by motcwang** [comment]
更新了最新版本，还是有问题， @icezohu @Boshen 我这个日志是执行`npm start`后出现的，导致页面一直在开始的loading页面里。

**Comment by Boshen** [comment]
@motcwang 你可以帮我排查下这 module 去哪儿了。。

**Comment by icezohu** [comment]
@motcwang 可能是因为cookie的问题有多处，分别在两个子项目里面，全局搜索一下全部改吧。。。我复制了本地版本，没有跟github版本，不知道现在怎么样了。

**Comment by motcwang** [comment]
可以了，非常感谢。
