### ISSUE TITLE
建议用户反馈重定向到 GitHub 来

### ISSUE THREAD

**Issue by jiyinyiyong** [jianliaoim/talk-os#31]
发送到内部的反馈现在其实没人处理

https://jianliao.com/team/55b8b871e46ec72865a8f027/room/55da708a73a1cf7d03b0a762

**Comment by sailxjx** [comment]
到了 GitHub 你也不会处理吧 🐽

**Comment by jiyinyiyong** [comment]
不是我处理啊. 但是这种情况下还有人往里边发消息不是很奇怪吗

**Comment by sailxjx** [comment]
我看了下这个地方的反馈不是直接发送到话题中的，是从很多地方通过 webhook 推送到简聊中的，转发到   GitHub 估计有点困难。
而且这里主要是交流代码问题，产品的问题就不在这里解决了。

**Comment by jiyinyiyong** [comment]
我觉得直接关闭反馈按钮都可以了.
