### ISSUE TITLE
npm run init 报错

### ISSUE THREAD

**Issue by frankwei98** [jianliaoim/talk-os#34]
使用CentOS 7

使用着npm 2.15.1
使用着node v4.4.4

> [root@localhost talk-os]# npm run init
> 
> > talk-os@1.0.0 init /root/talk-os
> > ./init.sh
> 
> Install talk-api2x dependencies
> Install talk-web dependencies and build front-end assets
> npm WARN package.json talk-web@3.2.2 No license field.
> npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
> npm ERR! node v4.4.4
> npm ERR! npm  v2.15.1
> npm ERR! code ETARGET
> 
> npm ERR! notarget No compatible version found: lodash._arrayincludes@'>=3.0.0 <4.0.0'
> npm ERR! notarget Valid install targets:
> npm ERR! notarget ["4.0.0"]
> npm ERR! notarget 
> npm ERR! notarget This is most likely not a problem with npm itself.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget 
> npm ERR! notarget It was specified as a dependency of 'lodash.uniq'
> npm ERR! notarget 

> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/talk-os/talk-web/npm-debug.log

**Comment by Boshen** [comment]
lodash，node， npm 版本开始起冲突了。 你要是能找到原因就先谢谢啦 :smile:

**Comment by shuinan** [comment]
就是这个lodash，很多地方要求的版本不一致，有的是3...,有的是4....。 同一个项目中互不相同，怎么办理？
