### ISSUE TITLE
npm run init失败怎么办？

### ISSUE THREAD

**Issue by BUPTWYX** [jianliaoim/talk-os#38]
安装很多依赖时都报错了，有的更名了，怎么办呀？

**Comment by Boshen** [comment]
很多报错具体是什么报错

**Comment by BUPTWYX** [comment]
$ npm run init

> talk-os@1.0.0 init C:\Users\w219\Desktop\talk-os-master\talk-os-master
> ./init.sh

'.' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                      node_modules\\npm\\bin\\npm-cli.js" "run" "init"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! talk-os@1.0.0 init: `./init.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talk-os@1.0.0 init script './init.sh'.
npm ERR! This is most likely a problem with the talk-os package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./init.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls talk-os
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\w219\Desktop\talk-os-master\talk-os-master\npm-debug.log

**Comment by BUPTWYX** [comment]
双击init.sh是
Install talk-api2x dependencies
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install th                                   e latest version of pug instead of jade
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie                                    https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.3"                                   ,"npm":"2.14.7"})

> hiredis@0.4.1 install C:\Users\w219\Desktop\talk-os-master\talk-os-master\talk                                   -api2x\node_modules\hiredis
> node-gyp rebuild


C:\Users\w219\Desktop\talk-os-master\talk-os-master\talk-api2x\node_modules\hire                                   dis>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modul                                   es\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )                                     else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT                                   HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod                                   e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node                                   -gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej                                   s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\w219\Desktop\talk-os-master\talk-os-master\talk-api2x\node                                   _modules\hiredis
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

请求指教

**Comment by Brooooooklyn** [comment]
windows 用户请安装 Python 并将可执行文件目录加到 path

**Comment by BUPTWYX** [comment]
安装完python还是

**Comment by BUPTWYX** [comment]
安装完python还是

> talk-os@1.0.0 init C:\Users\wyx\Desktop\talk-os-master\talk-os-master
> ./init.sh

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.14393
后面一样的

**Comment by Brooooooklyn** [comment]
安装 git bash，然后再到 git bash 中执行 `npm start`， cmd 无法识别 `.sh` 脚本

**Comment by jhooo** [comment]
@BUPTWYX 
windows下
将package.json第8行  "./init.sh" 改为 " sh init.sh"
然后使用git bash执行

**Comment by jhooo** [comment]
如果window出现node-gyp
可以查看

http://cnodejs.org/topic/53040bc95366a72a2c2128b9

**Comment by ymy1203** [comment]
window 会有各种各样的错误。换linux就好了。一直就在虚拟机上跑。。。
