### ISSUE TITLE
Fail to create team

### ISSUE THREAD

**Issue by AoranZhao** [jianliaoim/talk-os#40]
按照readme指示架设起简聊，注册完用户后创建Team，结果卡这个过程中。jianliao.com中POST /teams后，response中默认含有两个member和一个room。在我架设的简聊中，同样的过程，response中member和room为空，进而GET /notification?_teamId= 和GET/rooms 出现403错误。返回{code: 204, message: "非 team 成员"}。求助，在线等～～～～

我架设简聊的link: http://talk.zhaoaoran.ca

**Comment by sailxjx** [comment]
这个地址无法访问呐

**Comment by AoranZhao** [comment]
OMG, 天啊，我这里能正常访问，不会被墙了吧。有没有什么别的方法可以看到呢

**Comment by sailxjx** [comment]
是被墙了。
创建过程没问题，后台有错误 log 吗？

**Comment by AoranZhao** [comment]
我截了两个图片，这是点击创建Team时，developer tool的显示。如果能有个远程桌面，不知道会不会有效，或者你看看还需要什么地方的信息，我可以再截给你。

用github的master分支，node和npm版本都符合要求，搭建方式也严格按github上指示搭建。

除此之外，制作过两处修改，1. 更改config文件夹内localhost为主机地址，mongodb和redis相关的除外； 2. talk-account/client/controller/index.coffee, line 5之后添加一行, cookie = cookie.cookie，否则提示cookie.set不是function。其它地方没有修改过。

**Comment by sailxjx** [comment]
你在 mongodb 里面查查成员信息有没有 `db.members.find({team: ObjectId('593763132aa423722d5e90b5')})`

**Comment by AoranZhao** [comment]
我找了一下，可惜没有members这个collection。talk数据库里有三个collections：teams，users，preferences。我找了下users里，是没有的

**Comment by sailxjx** [comment]
在这上面 https://github.com/jianliaoim/talk-os/blob/master/talk-api2x/server/observers/team.coffee#L46 加几行打点 log 出来吧
```
console.log('isnew', @isNew)
console.log('team', this)
```

**Comment by AoranZhao** [comment]
Hi, 不好意思久等啦。

我加了在46行前后各加了两行，重新npm run init 和npm start， 新建team时好像console并没有显示，我重复了几次，都是如此。

**Comment by sailxjx** [comment]
你用的 mongoose 版本是多少？固定在 4.1.0 版本再试一次吧

**Comment by AoranZhao** [comment]
Great!! 更改mongose版本4.1.0后创建team成功了。只是console里出现了大量的warning，关于type Map 的 prop ‘core’, ‘route’, ‘router’, ‘user’, ‘channel’…..，这些是不是有可能是Schema的问题呢？

**Comment by sailxjx** [comment]
没有关系

**Comment by AoranZhao** [comment]
Thank you very ～much！
